<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>all task API</description>
   <name>Test API Scenario</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d784d1f8-e3b7-476a-a6fc-f7a89b2de5f0</testSuiteGuid>
   <testCaseLink>
      <guid>c3554ea5-bfec-4605-b5f7-064c440d27a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API/Login with empty password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c79a8200-acef-4d14-9f27-fa8e0af8ca32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66507dcd-3a9a-4557-b6fc-113221684198</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90083e49-9645-45c2-98fc-bdab5990e3e2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e0e17fc-f111-4403-83ac-c04517ddb836</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API/Login with empty username</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e5a4e26-b68c-4403-a3c7-03fe119cc3e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e3d33ec-5f39-4560-b4ff-cd0a45c73034</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>762109ae-3870-419d-980b-481dad0cde33</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8caa95ea-57d4-435e-84f4-2675a15381b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API/Login with wrong organization name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59cb9c9b-e626-43a7-bb15-50f574905b9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>484652d7-88c1-4995-9096-74643b538d6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>951eaf61-6650-4b12-b6eb-d6b000692e1a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6e400eac-c86c-4627-ac33-47d9bf8b23e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API/Login with wrong username and password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7315d81f-8569-41da-b634-cb42dd8e7229</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90d2987a-8233-42c0-b144-2e5fa139fd78</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>732e28cc-9c15-45c1-9cdb-fc8b397fa26a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>13b15963-c109-45da-9f13-83e269ef4ed8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API/Organization login with invalid name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47632c91-da08-4a9e-93a0-b57cc9f62e95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8c6e47b-c3fe-4f09-b950-a05a1dc08d62</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d985b037-cc31-478d-a7ac-eee878555cef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API/Organization Login with valid name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e8c1d71-2484-4b4b-9a08-70eb0bbf8a7c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
